-- =========================================================
-- scoletta@ads.it - History Records Plugin
-- Struttura DDL + dictionary records (AD_Element, AD_Reference, AD_Ref_List,
-- AD_Table, AD_Column) per Postgres. Eseguito da HistoryRecordsCoreActivator
-- via JDBC diretto (bypass model layer → no MColumn.syncDatabase → no lock).
--
-- Idempotenza per-statement: l'activator riconosce SQLSTATE 23505/42701/42P07
-- (Postgres) e ORA-00001/01430/00955 (Oracle) come skip silenzioso.
-- =========================================================

-- ===== AD_EntityType (FINHST) — FK su cui dipendono tutti i record FINHST =====
INSERT INTO AD_EntityType (AD_EntityType_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,EntityType,ModelPackage,AD_EntityType_UU) VALUES (1000026,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Finmatica History Records Management','FINHST','it.finmatica.history.records.model','b47115b8-5639-4d9c-935e-58eb7febaeb3');

-- ===== AD_Element (FINHST) =====
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001798,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'HST_HistoryMode','History Mode','Modalità Storicizzazione','History Mode for the table',NULL,'FINHST','f1d144d8-7400-4bc6-9766-02e31590454a');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001799,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'HST_IsForceHstApplication','Is Force Hst Application','Forza Applicabilità Storicizzazione','Force Applicability of the Historicizing ',NULL,'FINHST','abbccc1c-7494-4882-98e1-1cb24b5810fb');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001800,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'HST_IsHstColumn','Is Hst Column','Colonna Storicizzata','Is Historicised Column',NULL,'FINHST','6c49b8af-4ea2-4389-82cc-b224459246ea');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001801,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'HST_UpdCheckConf_ID','Update Check Configuration','Configurazione Controlli',NULL,NULL,'FINHST','1e81d4c7-1363-4d63-8e6e-f912f40e2595');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001802,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'HST_DestTable_ID','Destination Table','Tabella di Destinazione','It represent the table of destination',NULL,'FINHST','f0a5478d-2ae1-4fba-bf69-63af2fe9b548');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001803,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'HST_CheckQuery','Check Query','Query di Verifica','Query for the check',NULL,'FINHST','7093dee6-3699-4b3b-ac2a-abfc040e9df2');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001804,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'HST_CheckUserDef','Check User Definition','Determinazione Utente Destinatario','Query for user definition',NULL,'FINHST','e358fd4c-e278-4325-97fb-0eab4940cb9f');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001805,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'HSTFromDate','From Date','Data Da',NULL,NULL,'FINHST','7a1c316a-619a-46f9-9397-228d7d705edf');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001806,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'HSTToDate','To Date','Data A',NULL,NULL,'FINHST','47e4fa2f-5eb8-4921-9fa4-ee671096ee18');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001807,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'HSTIsPrimaryTree','Primary Tree','Albero Principale',NULL,NULL,'FINHST','98ac4eff-67a2-4d59-88ae-124977f504a1');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001808,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'HSTParentTree_ID','Parent Tree','Albero Padre',NULL,NULL,'FINHST','2967640c-0a26-4658-80b0-4bdf1eac7685');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001809,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'T_HSTCheckResults_ID','History Check Result','Risultato controllo impatto',NULL,NULL,'FINHST','edef66b8-6d0a-4d2d-a18d-d6db545cace1');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001810,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'HST_Record_ID','History Record','Record Storico',NULL,NULL,'FINHST','4f6e3b25-6ab9-43e2-adba-a32bf6ea287a');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001811,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'HST_DateSourceConf_ID','Source Date Configuration','Configurazione Sorgenti','Source Date Configuration for the history',NULL,'FINHST','46d9d1cc-35f9-42a6-a742-ca1bb4d30d9f');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001813,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'HSTActualRecord','History Actual Record','Record Storico Attuale',NULL,NULL,'FINHST','c8f27a2d-97c0-4d0d-a9b7-be3fa54cb4c9');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001932,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'M_Product_HST_ID','Product HST','Product HST',NULL,NULL,'FINHST','374acbe0-d9f6-4109-9b88-34c024994e5f');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001933,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'F3P_PRODUCT_BRAND_ID','F3P_PRODUCT_BRAND_ID','F3P_PRODUCT_BRAND_ID',NULL,NULL,'FINHST','49f5c565-fe0b-450d-a573-ab5f579f96c5');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001934,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'M_Product_HST_UU','M_Product_HST_UU','M_Product_HST_UU',NULL,NULL,'FINHST','9fc40855-ed35-47a5-89f6-94e10357f050');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001935,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'M_Warehouse_HST_ID','Warehouse HST','Warehouse HST',NULL,NULL,'FINHST','24d0b61c-96ae-40d2-85b6-8de2f57ed753');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001936,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'M_Warehouse_HST_UU','M_Warehouse_HST_UU','M_Warehouse_HST_UU',NULL,NULL,'FINHST','d7b0e551-9df2-40d4-b90d-078b93ba32fc');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001937,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'C_BPartner_HST_ID','Business Partner HST','Business Partner HST',NULL,NULL,'FINHST','043c7e8a-994b-4d2d-a450-be8ba55c23d9');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001938,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'C_BPartner_HST_UU','C_BPartner_HST_UU','C_BPartner_HST_UU',NULL,NULL,'FINHST','3177186a-a6a6-4bc1-8474-d139517ca056');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001939,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'M_Product_Category_HST_ID','Product Category History','Product Category History',NULL,NULL,'FINHST','6d6eccd1-5910-45eb-a2ea-e12b06f32bc7');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1001940,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'M_Product_Category_HST_UU','M_Product_Category_HST_UU','M_Product_Category_HST_UU',NULL,NULL,'FINHST','7b342e17-8e3b-4333-8b85-c7a35881f108');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1002628,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'HST_UpdCheckConf_UU','HST_UpdCheckConf_UU','HST_UpdCheckConf_UU',NULL,NULL,'FINHST','9e9afeb5-5a34-4efe-9b01-da7eaa262061');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1002629,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'HST_DateSourceConf_UU','HST_DateSourceConf_UU','HST_DateSourceConf_UU',NULL,NULL,'FINHST','3a6b40ad-2189-415d-a3ae-63e84e7c13fc');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1010019,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'LIT_TaxPayerType_HST_ID','LIT_TaxPayerType_HST','LIT_TaxPayerType_HST',NULL,NULL,'FINHST','7c22c738-c1c9-4999-b547-56fea98d2355');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1010020,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'LIT_TaxPayerType_HST_UU','LIT_TaxPayerType_HST_UU','LIT_TaxPayerType_HST_UU',NULL,NULL,'FINHST','4c867fde-6425-418c-9bb6-3329570974f0');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1010021,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'LIT_TaxPayerType_UU','LIT_TaxPayerType_UU','LIT_TaxPayerType_UU',NULL,NULL,'FINHST','94d47dd9-fda9-4af1-824e-3e1fe539e881');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1013307,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'FINCA_ASSET_MOV_REASON_HST_ID','FINCA_ASSET_MOV_REASON_HST','FINCA_ASSET_MOV_REASON_HST',NULL,NULL,'FINHST','dcdede2a-eb04-4555-a2de-77bb0d9206ae');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1013308,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'FINCA_ASSET_MOV_REASON_HST_UU','FINCA_ASSET_MOV_REASON_HST_UU','FINCA_ASSET_MOV_REASON_HST_UU',NULL,NULL,'FINHST','42fb6c82-a9c1-4938-9e9c-ed7be24abb41');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1013462,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'FINCA_ASSET_CATEGORY_HST_ID','FINCA_ASSET_CATEGORY_HST','FINCA_ASSET_CATEGORY_HST',NULL,NULL,'FINHST','431ba335-a691-44c5-96ef-c16c01f860bf');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1013463,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'FINCA_ASSET_CATEGORY_HST_UU','FINCA_ASSET_CATEGORY_HST_UU','FINCA_ASSET_CATEGORY_HST_UU',NULL,NULL,'FINHST','00891bff-9eb2-492b-8dea-2a9ef2dc0b8a');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1015776,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'FINCE_Activity_HST_ID','Storico attività','Storico attività',NULL,NULL,'FINHST','538aafdd-850c-4b17-b957-4ee22ed2e277');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1015777,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'FINCE_Activity_HST_UU','FINCE_Activity_HST_UU','FINCE_Activity_HST_UU',NULL,NULL,'FINHST','db983d59-c484-462d-9f3e-7d51b97069f0');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1018718,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'M_Replenish_HST_ID','Replenish HST','Replenish HST','Storico Riapprovvigionamento',NULL,'FINHST','ff967a51-c4b6-45fb-b85e-5a5add9dcefd');
INSERT INTO AD_Element (AD_Element_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,ColumnName,Name,PrintName,Description,Help,EntityType,AD_Element_UU) VALUES (1018719,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'M_Replenish_HST_UU','M_Replenish_HST_UU','M_Replenish_HST_UU','Storico Riapprovvigionamento UU',NULL,'FINHST','e0c01a5c-1cb1-4290-96f9-319e3cf1d07a');

-- ===== AD_Reference (tutte le FINHST) =====
INSERT INTO AD_Reference (AD_Reference_ID,Name,Description,Help,ValidationType,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,EntityType,AD_Reference_UU,IsOrderByValue) VALUES (1000236,'HSTActualRecord List',NULL,NULL,'L',0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'FINHST','7d6b8a5e-e213-4ebc-aa8b-e5cf4e8e1da1','N');
INSERT INTO AD_Reference (AD_Reference_ID,Name,Description,Help,ValidationType,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,EntityType,AD_Reference_UU,IsOrderByValue) VALUES (1000237,'HST_HistoryMode','HST_HistoryMode',NULL,'L',0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'FINHST','4e34deb2-1643-4b77-8f87-a46c405a5377','N');
INSERT INTO AD_Reference (AD_Reference_ID,Name,Description,Help,ValidationType,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,EntityType,AD_Reference_UU,IsOrderByValue) VALUES (1000238,'HST_PrimaryTrees',NULL,NULL,'T',0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'FINHST','791f26a2-92b5-4c25-8700-016be77cf2bf','N');

-- ===== AD_Ref_List =====
INSERT INTO AD_Ref_List (AD_Ref_List_ID,AD_Reference_ID,Value,Name,Description,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,EntityType,AD_Ref_List_UU) VALUES (1000660,1000236,'F','Future',NULL,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'FINHST','ebf145aa-f769-4fa5-ba74-641806127980');
INSERT INTO AD_Ref_List (AD_Ref_List_ID,AD_Reference_ID,Value,Name,Description,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,EntityType,AD_Ref_List_UU) VALUES (1000658,1000236,'N','No',NULL,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'FINHST','ca57a721-2ee6-4c38-a6aa-5d0c039796a1');
INSERT INTO AD_Ref_List (AD_Ref_List_ID,AD_Reference_ID,Value,Name,Description,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,EntityType,AD_Ref_List_UU) VALUES (1000659,1000236,'Y','Yes',NULL,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'FINHST','e2549e24-58df-42a0-9825-41ac364e3224');
INSERT INTO AD_Ref_List (AD_Ref_List_ID,AD_Reference_ID,Value,Name,Description,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,EntityType,AD_Ref_List_UU) VALUES (1004309,1000237,'L','Log',NULL,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'FINHST','8e922445-2c7b-4753-8b6a-597b3c21b7a8');
INSERT INTO AD_Ref_List (AD_Ref_List_ID,AD_Reference_ID,Value,Name,Description,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,EntityType,AD_Ref_List_UU) VALUES (1000661,1000237,'N','None',NULL,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'FINHST','52d1d901-592d-43bf-89a3-e7e965a22c2f');
INSERT INTO AD_Ref_List (AD_Ref_List_ID,AD_Reference_ID,Value,Name,Description,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,EntityType,AD_Ref_List_UU) VALUES (1000662,1000237,'S','Historicizing',NULL,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'FINHST','b7654240-8e17-42a4-9662-feb357a5cf5a');
INSERT INTO AD_Ref_List (AD_Ref_List_ID,AD_Reference_ID,Value,Name,Description,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,EntityType,AD_Ref_List_UU) VALUES (1000663,1000237,'T','Time Machine',NULL,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'FINHST','17dea11e-73de-4aeb-8450-415d8c026f9c');
INSERT INTO AD_Ref_List (AD_Ref_List_ID,AD_Reference_ID,Value,Name,Description,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,EntityType,AD_Ref_List_UU) VALUES (1000664,1000237,'V','View',NULL,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'FINHST','048f2d15-347c-45d0-bb96-ec93833618a7');

-- ===== AD_Ref_Table (HST_PrimaryTrees) =====
INSERT INTO AD_Ref_Table (AD_Reference_ID,AD_Table_ID,AD_Key,AD_Display,WhereClause,EntityType,AD_Ref_Table_UU,IsValueDisplayed,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy) VALUES (1000238,288,2856,2856,'AD_Tree.HSTIsPrimaryTree = ''Y''','FINHST','0f24de7c-58c9-419e-9d26-3804250b5171','N',0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0);

-- ===== AD_Val_Rule (FINHST) =====
INSERT INTO AD_Val_Rule (AD_Val_Rule_ID,Name,Description,Type,Code,EntityType,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,AD_Val_Rule_UU) VALUES (1000138,'AD_Tree of same type',NULL,'S','AD_Tree.TreeType=''@TreeType@'' AND ((AD_Tree.ad_table_id is null and @AD_Table_ID@=0) or AD_Tree.ad_table_id = @AD_Table_ID@) AND AD_Tree.AD_Client_ID=@AD_Client_ID@','FINHST',0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'3b11e4e8-eb31-472c-b380-f1132c997b51');

-- ===== AD_Table (4 tabelle plugin) =====
INSERT INTO AD_Table (AD_Table_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,TableName,Description,Help,AccessLevel,EntityType,AD_Table_UU,IsView,AD_Window_ID) VALUES (1000192,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Source Date Configuration','HST_DateSourceConf',NULL,NULL,'7','FINHST','fbc10d43-ada1-4863-9229-b0488522a3ff','N',NULL);
INSERT INTO AD_Table (AD_Table_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,TableName,Description,Help,AccessLevel,EntityType,AD_Table_UU,IsView,AD_Window_ID) VALUES (1000190,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Table Rules','HST_TableRules','Regole Tabella Storicizzata',NULL,'4','FINHST','d700e733-2703-49e0-b894-f9bb3244e612','Y',NULL);
INSERT INTO AD_Table (AD_Table_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,TableName,Description,Help,AccessLevel,EntityType,AD_Table_UU,IsView,AD_Window_ID) VALUES (1000189,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Update Check Configuration','HST_UpdCheckConf',NULL,NULL,'7','FINHST','ce6dd2b1-d55b-4abf-b209-dbfa671885a6','N',NULL);
INSERT INTO AD_Table (AD_Table_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,TableName,Description,Help,AccessLevel,EntityType,AD_Table_UU,IsView,AD_Window_ID) VALUES (1000191,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'History Check Result','T_HSTCheckResults',NULL,NULL,'3','FINHST','0212dadd-76f5-4c36-b42e-ea43fb01f8fc','N',NULL);

-- ===== AD_Column (9 iniettate + colonne 4 tabelle plugin) =====
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005978,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Is Hst Column','HST_IsHstColumn','Is Historicised Column',NULL,101,20,NULL,1,'N','N','Y','N','N',0,'N',1001800,'Y','N','FINHST','Y','N','N','Y','b00142af-eee3-4f60-bd46-5d2559406ee2','Y','N',NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005975,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Info Window','AD_InfoWindow_ID','Info and search/select Window','The Info window is used to search and select records as well as display information relevant to the selection.',284,30,NULL,10,'N','N','N','N','N',0,'N',3068,'N','N','FINHST','Y','N','N','Y','0a8f4ec7-f26c-4062-aa5d-cf93e64fb45c','Y',NULL,NULL,'HST_InfoWindow','N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005976,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'History Mode','HST_HistoryMode','History Mode for the table',NULL,100,17,1000237,1,'N','N','Y','N','N',0,'N',1001798,'Y','N','FINHST','Y','N','N','Y','4a2d2c54-b88e-4efc-bb04-669363c178c1','Y','N',NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005977,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Is Force Hst Application','HST_IsForceHstApplication','Force Applicability of the Historicizing ',NULL,100,20,NULL,1,'N','N','Y','N','N',0,'N',1001799,'Y','N','FINHST','Y','N','N','Y','2f895ea7-3780-448f-8861-754b96511117','Y','N',NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1014312,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Element','C_Element_ID','Accounting Element',NULL,288,19,NULL,10,'N','N','N','N','N',0,'N',199,'Y','N','FINHST','Y','N','N','Y','68dea70f-4df5-4753-98f1-d249a196a6c0','Y',NULL,NULL,'CElement_ADTree','N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006004,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'From Date','HSTFromDate',NULL,NULL,288,15,NULL,7,'N','N','N','N','N',0,'N',1001805,'Y','N','FINHST','Y','N','N','Y','34f0e36f-1841-48db-bcbc-16371d887546','Y','current_timestamp',NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006006,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Primary Tree','HSTIsPrimaryTree',NULL,NULL,288,20,NULL,1,'N','N','N','N','N',0,'N',1001807,'Y','N','FINHST','Y','N','N','Y','928d81a0-0b16-4fac-9c19-7ef13e3a6956','Y','''N''',NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006007,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Parent Tree','HSTParentTree_ID',NULL,NULL,288,30,1000238,10,'N','N','N','N','N',0,'N',1001808,'Y','N','FINHST','Y','N','N','Y','5c99dd19-3289-4026-beb1-0ebff0fce954','Y',NULL,1000138,'adtree_parenttree','N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006005,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'To Date','HSTToDate',NULL,NULL,288,15,NULL,7,'N','N','N','N','N',0,'N',1001806,'Y','N','FINHST','Y','N','N','Y','4c58592c-4cca-4d51-b070-27e1764f9e69','Y','current_timestamp',NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006027,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Client','AD_Client_ID',NULL,NULL,1000192,19,NULL,22,'N','N','Y','N','N',0,'N',102,'N','N','FINHST','Y','N','N','N','80cae536-ed5d-4d52-a112-3ab42818bee9','N','@#AD_Client_ID@',129,'AD_Client_HST_DateSourceConf','N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006028,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Organization','AD_Org_ID',NULL,NULL,1000192,19,NULL,22,'N','N','Y','N','N',0,'N',113,'N','N','FINHST','Y','N','N','N','dd5e5916-4b04-4f4d-8b9c-02138730655e','N','@#AD_Org_ID@',104,'AD_Org_HST_DateSourceConf','N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006025,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Table','AD_Table_ID',NULL,NULL,1000192,19,NULL,10,'N','N','N','N','N',0,'N',126,'Y','N','FINHST','Y','N','N','Y','a8b68c8c-b4dd-4c9f-a44e-83cf5d6ced04','Y',NULL,NULL,'AD_Table_HST_DateSourceConf','N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006030,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Created','Created',NULL,NULL,1000192,16,NULL,7,'N','N','N','N','N',0,'N',245,'N','N','FINHST','Y','N','N','N','5d9f3481-7f41-454c-a694-28ae49e2fffd','N','SYSDATE',NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006031,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Created By','CreatedBy',NULL,NULL,1000192,30,110,22,'N','N','N','N','N',0,'N',246,'N','N','FINHST','Y','N','N','N','8fa031b8-ccda-4853-9ef9-2a151ea25c7b','N',NULL,NULL,NULL,'D','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006024,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Source Date Configuration','HST_DateSourceConf_ID','Source Date Configuration for the history',NULL,1000192,13,NULL,22,'Y','N','Y','N','N',0,'N',1001811,'N','N','FINHST','Y','N','N','Y','d53d90f1-4359-4ed2-b169-7b4c6df8e553','N',NULL,NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1009360,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'HST_DateSourceConf_UU','HST_DateSourceConf_UU',NULL,NULL,1000192,10,NULL,36,'N','N','N','N','N',0,'N',1002629,'Y','N','FINHST','Y','N','N','Y','17b5ffbb-79d4-484f-a247-9e9c1727e656','N',NULL,NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006029,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Active','IsActive',NULL,NULL,1000192,20,NULL,1,'N','N','Y','N','N',0,'N',348,'Y','N','FINHST','Y','N','N','Y','28bdd890-9c7c-47f0-8a4b-2200e3152e66','N','Y',NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006026,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Script','Script','Dynamic Java Language Script to calculate result',NULL,1000192,14,NULL,2000,'N','N','N','N','N',0,'N',1718,'Y','N','FINHST','Y','N','N','Y','ba957581-5e3c-483f-86c6-dcc20b90d284','Y',NULL,NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006032,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Updated','Updated',NULL,NULL,1000192,16,NULL,7,'N','N','N','N','N',0,'N',607,'N','N','FINHST','Y','N','N','N','396f3a3c-2ca5-4eb8-9152-ff0a17c782a2','N','SYSDATE',NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006033,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Updated By','UpdatedBy',NULL,NULL,1000192,30,110,22,'N','N','N','N','N',0,'N',608,'N','N','FINHST','Y','N','N','N','8cc12ae8-8ff3-4d07-9768-c6483355823c','N',NULL,NULL,'updatedby_hstdatesourceconf','N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005996,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Client','AD_Client_ID',NULL,NULL,1000190,19,NULL,10,'N','N','N','N','N',NULL,'N',102,'N','N','FINHST','Y','N','N','N','55a435af-936a-4f77-ba19-f725f0028be6','N','@#AD_Client_ID@',129,NULL,'D','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005997,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Organization','AD_Org_ID',NULL,NULL,1000190,19,NULL,10,'N','N','N','N','N',NULL,'N',113,'N','N','FINHST','Y','N','N','N','1bfd9850-8121-46fb-a012-5a5459a51daa','N','@#AD_Org_ID@',104,NULL,'D','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005994,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Rule','AD_Rule_ID',NULL,NULL,1000190,19,NULL,10,'N','N','N','N','N',NULL,'N',53332,'N','N','FINHST','Y','N','N','Y','d6f49e05-0343-4959-af05-fbd1a4e0114f','Y',NULL,NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006003,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Table','AD_Table_ID',NULL,NULL,1000190,19,NULL,10,'N','Y','N','N','N',NULL,'N',126,'N','N','FINHST','Y','N','N','Y','f49669ee-846c-48a4-a68a-43f7c33fc648','Y',NULL,NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005999,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Created','Created',NULL,NULL,1000190,16,NULL,29,'N','N','N','N','N',NULL,'N',245,'N','N','FINHST','Y','N','N','N','3811ec2d-fff0-48eb-b0e3-ec45615ddcba','N','SYSDATE',NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006000,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Created By','CreatedBy',NULL,NULL,1000190,30,110,10,'N','N','N','N','N',NULL,'N',246,'N','N','FINHST','Y','N','N','N','a8e051f4-2126-466e-a419-05b0fe5138e3','N',NULL,NULL,NULL,'D','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005993,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Event Model Validator','EventModelValidator',NULL,NULL,1000190,17,53237,4,'N','N','N','N','Y',NULL,'N',53338,'N','N','FINHST','Y','N','N','Y','71706862-e598-4991-8d9a-e1155526ceff','Y',NULL,NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005998,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Active','IsActive',NULL,NULL,1000190,20,NULL,1,'N','N','N','N','N',NULL,'N',348,'N','N','FINHST','Y','N','N','Y','3e70ec9b-d19b-4df1-aafa-c2562629ca8d','N','Y',NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005995,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Script','Script','Dynamic Java Language Script to calculate result',NULL,1000190,14,NULL,4000,'N','N','N','N','N',NULL,'N',1718,'N','N','FINHST','Y','N','N','Y','72735833-3582-441f-96d0-9243a7a5fcb9','Y',NULL,NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006001,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Updated','Updated',NULL,NULL,1000190,16,NULL,29,'N','N','N','N','N',NULL,'N',607,'N','N','FINHST','Y','N','N','N','c6a7ad3f-ae07-4634-8e58-f55eb1e38a48','N','SYSDATE',NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006002,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Updated By','UpdatedBy',NULL,NULL,1000190,30,110,10,'N','N','N','N','N',NULL,'N',608,'N','N','FINHST','Y','N','N','N','9e67e4bc-a61c-4ea1-a57b-08ac45a87825','N',NULL,NULL,NULL,'D','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005992,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Description','Description',NULL,NULL,1000189,10,NULL,255,'N','N','N','N','N',0,'N',275,'Y','Y','FINHST','Y','N','N','Y','97efec6e-ba25-405f-b014-36782a51fb46','Y',NULL,NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1009359,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'HST_UpdCheckConf_UU','HST_UpdCheckConf_UU',NULL,NULL,1000189,10,NULL,36,'N','N','N','N','N',0,'N',1002628,'Y','N','FINHST','Y','N','N','Y','9afa3946-ef9e-413b-b716-9258e7274e70','N',NULL,NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005991,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Name','Name',NULL,NULL,1000189,10,NULL,60,'N','N','N','N','Y',0,'N',469,'Y','Y','FINHST','Y','N','N','Y','dd13cb4c-ae2c-41ed-a504-8b3236fb3d8a','Y',NULL,NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005980,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Client','AD_Client_ID',NULL,NULL,1000189,19,NULL,10,'N','N','Y','N','N',NULL,'N',102,'N','N','FINHST','Y','N','N','N','d301fa9b-1e8c-4ae4-867d-0a94d3da45d2','N','@#AD_Client_ID@',129,'adclient_HST_UpdCheckConf','N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005981,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Organization','AD_Org_ID',NULL,NULL,1000189,19,NULL,10,'N','N','Y','N','N',NULL,'N',113,'N','N','FINHST','Y','N','N','N','bac353ce-62ad-4983-85d2-3660682c2dbc','N','@#AD_Org_ID@',104,'ad_org_HST_UpdCheckConf','N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005987,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Table','AD_Table_ID',NULL,NULL,1000189,30,NULL,10,'N','N','Y','N','N',NULL,'N',126,'Y','N','FINHST','Y','N','N','Y','5f3607dc-51ca-4d4a-b126-1c402f80acde','Y',NULL,NULL,'ad_table_HST_UpdCheckConf','N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005983,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Created','Created',NULL,NULL,1000189,16,NULL,29,'N','N','Y','N','N',NULL,'N',245,'N','N','FINHST','Y','N','N','N','551f2808-2a88-4054-b5fe-7faaa6a26e61','N','SYSDATE',NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005985,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Created By','CreatedBy',NULL,NULL,1000189,30,110,10,'N','N','Y','N','N',NULL,'N',246,'N','N','FINHST','Y','N','N','N','98deae6d-19ea-4a43-8128-719ca4df697d','N',NULL,NULL,NULL,'D','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005989,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Check Query','HST_CheckQuery','Query for the check',NULL,1000189,14,NULL,4000,'N','N','N','N','N',NULL,'N',1001803,'Y','N','FINHST','Y','N','N','Y','be1b65f6-051c-4b80-8a09-6eb570947fcc','Y',NULL,NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005990,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Check User Definition','HST_CheckUserDef','Query for user definition',NULL,1000189,14,NULL,4000,'N','N','N','N','N',NULL,'N',1001804,'Y','N','FINHST','Y','N','N','Y','f792e1d3-4e25-4abd-90d3-937f5adbc691','Y',NULL,NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005988,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Destination Table','HST_DestTable_ID','It represent the table of destination',NULL,1000189,30,53290,10,'N','N','Y','N','N',NULL,'N',1001802,'Y','N','FINHST','Y','N','N','Y','16926f30-9ecf-4c32-95b4-248805a570e5','Y',NULL,NULL,'ad_tableDest_HST_UpdCheckConf','N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005979,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Update Check Configuration','HST_UpdCheckConf_ID',NULL,NULL,1000189,13,NULL,10,'Y','N','Y','N','N',NULL,'N',1001801,'N','N','FINHST','Y','N','N','Y','56ac05cb-314a-425c-972b-c729ca78b807','N',NULL,NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005982,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Active','IsActive',NULL,NULL,1000189,20,NULL,1,'N','N','Y','N','N',NULL,'N',348,'Y','N','FINHST','Y','N','N','Y','7c6fa6a4-5845-4172-b150-6f3fab5ddb35','N','Y',NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005984,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Updated','Updated',NULL,NULL,1000189,16,NULL,29,'N','N','Y','N','N',NULL,'N',607,'N','N','FINHST','Y','N','N','N','45305a23-04a2-4e54-a97a-18c80fa4e3b3','N','SYSDATE',NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1005986,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Updated By','UpdatedBy',NULL,NULL,1000189,30,110,10,'N','N','Y','N','N',NULL,'N',608,'N','N','FINHST','Y','N','N','N','f51284e7-336b-4de8-928c-eea7b8ea077a','N',NULL,NULL,NULL,'D','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006017,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Client','AD_Client_ID',NULL,NULL,1000191,19,NULL,22,'N','N','Y','N','N',0,'N',102,'N','N','FINHST','Y','N','N','N','bfa92b78-5b65-4c3f-a20d-3e364cb5c833','N','@#AD_Client_ID@',129,'AD_Client_HSTCheckResults','N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006018,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Organization','AD_Org_ID',NULL,NULL,1000191,19,NULL,22,'N','N','Y','N','N',0,'N',113,'N','N','FINHST','Y','N','N','N','3e8f247d-fd44-40a7-8b79-0d0cb6ff65d5','N','@#AD_Org_ID@',104,'AD_Org_HSTCheckResults','N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006009,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Process Instance','AD_PInstance_ID',NULL,NULL,1000191,30,NULL,22,'N','Y','N','N','N',0,'N',114,'N','N','FINHST','Y','N','N','Y','2d43c7a4-c198-4cc4-a64f-890b6c5f4337','Y',NULL,NULL,'ad_pinstance_hst_CheckResult','N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006010,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Table','AD_Table_ID',NULL,NULL,1000191,19,NULL,10,'N','N','N','N','N',0,'N',126,'Y','N','FINHST','Y','N','N','Y','771fb589-5408-44c6-98a0-42766e17e40e','Y',NULL,NULL,'AD_Table_hst_CheckResults','N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006016,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'User/Contact','AD_User_ID','Utente',NULL,1000191,19,NULL,10,'N','N','N','N','N',0,'N',138,'N','N','FINHST','Y','N','N','Y','7562d975-56c7-4ed3-896e-6448269ad9b7','Y',NULL,NULL,'AD_User_hst_CheckResults','N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006020,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Created','Created',NULL,NULL,1000191,16,NULL,7,'N','N','N','N','N',0,'N',245,'N','N','FINHST','Y','N','N','N','2e4dec0f-b06f-4df4-9212-6ef1f11bfa03','N','SYSDATE',NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006021,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Created By','CreatedBy',NULL,NULL,1000191,30,110,22,'N','N','N','N','N',0,'N',246,'N','N','FINHST','Y','N','N','N','4c5c8b4b-3e24-4007-9aab-bce3ad725e49','N',NULL,NULL,NULL,'D','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006012,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Date From','DateFrom','Starting date for a range',NULL,1000191,15,NULL,7,'N','N','N','N','N',0,'N',1581,'Y','N','FINHST','Y','N','N','Y','3ace673a-5acb-47f9-93c8-9f3fe460cfec','Y',NULL,NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006015,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Description','Description',NULL,NULL,1000191,10,NULL,255,'N','N','N','N','N',0,'N',275,'Y','Y','FINHST','Y','N','N','Y','d53f59c2-18a0-4e3f-9fcd-83754135099f','Y',NULL,NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006013,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Destination Table','HST_DestTable_ID','It represent the table of destination',NULL,1000191,30,53290,10,'N','N','N','N','N',0,'N',1001802,'Y','N','FINHST','Y','N','N','Y','24e09d74-38d7-4a1f-865b-a15e52d03815','Y',NULL,NULL,'DestTable_hst_CheckResults','N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006014,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'History Record','HST_Record_ID',NULL,NULL,1000191,11,NULL,10,'N','N','N','N','N',0,'N',1001810,'Y','N','FINHST','Y','N','N','Y','bd6fb2e5-93ad-4281-8bc7-323f4991c6de','Y',NULL,NULL,NULL,NULL,'N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006019,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Active','IsActive',NULL,NULL,1000191,20,NULL,1,'N','N','Y','N','N',0,'N',348,'Y','N','FINHST','Y','N','N','Y','1e161e47-067e-4774-88b4-394ed67d1ac7','N','Y',NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006011,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Record ID','Record_ID','Direct internal record ID',NULL,1000191,28,NULL,22,'N','N','N','N','N',0,'N',538,'N','N','FINHST','Y','N','N','Y','336e3c3e-f91a-4b2a-8bff-a2a29897922c','Y',NULL,NULL,NULL,'N','B','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006008,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'History Check Result','T_HSTCheckResults_ID',NULL,NULL,1000191,13,NULL,22,'Y','N','Y','N','N',0,'N',1001809,'N','N','FINHST','Y','N','N','Y','04af29f8-0f74-4523-b985-d4bc8a01c04e','N',NULL,NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006022,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Updated','Updated',NULL,NULL,1000191,16,NULL,7,'N','N','N','N','N',0,'N',607,'N','N','FINHST','Y','N','N','N','beed4e83-a248-4c0d-85f2-67acb74e894a','N','SYSDATE',NULL,NULL,'N','N','N','N',0);
INSERT INTO AD_Column (AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ColumnName,Description,Help,AD_Table_ID,AD_Reference_ID,AD_Reference_Value_ID,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,DefaultValue,AD_Val_Rule_ID,FKConstraintName,FKConstraintType,IsToolbarButton,IsSecure,IsHtml,Version) VALUES (1006023,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Updated By','UpdatedBy',NULL,NULL,1000191,30,110,22,'N','N','N','N','N',0,'N',608,'N','N','FINHST','Y','N','N','N','688c99f3-6a9c-46a5-8ce4-8c3a45ef047c','N',NULL,NULL,NULL,'D','N','N','N',0);

-- ===== CREATE TABLE (Postgres dialect, no view) =====
CREATE TABLE HST_DateSourceConf (
  AD_Client_ID NUMERIC(10) NOT NULL,
  AD_Org_ID NUMERIC(10) NOT NULL,
  AD_Table_ID NUMERIC(10),
  Created TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CreatedBy NUMERIC(10),
  HST_DateSourceConf_ID NUMERIC(10) NOT NULL,
  HST_DateSourceConf_UU VARCHAR(36),
  IsActive CHAR(1) DEFAULT 'Y' NOT NULL,
  Script VARCHAR(2000),
  Updated TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UpdatedBy NUMERIC(10),
  CONSTRAINT hst_datesourceconf_pk PRIMARY KEY (HST_DateSourceConf_ID),
  CONSTRAINT hst_datesourceconf_uu_idx UNIQUE (HST_DateSourceConf_UU)
);

CREATE TABLE HST_UpdCheckConf (
  Description VARCHAR(255),
  HST_UpdCheckConf_UU VARCHAR(36),
  Name VARCHAR(60),
  AD_Client_ID NUMERIC(10) NOT NULL,
  AD_Org_ID NUMERIC(10) NOT NULL,
  AD_Table_ID NUMERIC(10) NOT NULL,
  Created TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CreatedBy NUMERIC(10) NOT NULL,
  HST_CheckQuery VARCHAR(4000),
  HST_CheckUserDef VARCHAR(4000),
  HST_DestTable_ID NUMERIC(10) NOT NULL,
  HST_UpdCheckConf_ID NUMERIC(10) NOT NULL,
  IsActive CHAR(1) DEFAULT 'Y' NOT NULL,
  Updated TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UpdatedBy NUMERIC(10) NOT NULL,
  CONSTRAINT hst_updcheckconf_pk PRIMARY KEY (HST_UpdCheckConf_ID),
  CONSTRAINT hst_updcheckconf_uu_idx UNIQUE (HST_UpdCheckConf_UU)
);

-- HST_TableRules is a VIEW — skipped (creazione separata)
CREATE TABLE T_HSTCheckResults (
  AD_Client_ID NUMERIC(10) NOT NULL,
  AD_Org_ID NUMERIC(10) NOT NULL,
  AD_PInstance_ID NUMERIC(10),
  AD_Table_ID NUMERIC(10),
  AD_User_ID NUMERIC(10),
  Created TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CreatedBy NUMERIC(10),
  DateFrom TIMESTAMP WITHOUT TIME ZONE,
  Description VARCHAR(255),
  HST_DestTable_ID NUMERIC(10),
  HST_Record_ID NUMERIC(11),
  IsActive CHAR(1) DEFAULT 'Y' NOT NULL,
  Record_ID CHAR(1),
  T_HSTCheckResults_ID NUMERIC(10) NOT NULL,
  Updated TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UpdatedBy NUMERIC(10),
  CONSTRAINT t_hstcheckresults_pk PRIMARY KEY (T_HSTCheckResults_ID)
);

-- ===== ALTER TABLE (colonne iniettate su tabelle standard) =====
ALTER TABLE AD_Table ADD COLUMN FIN_ForceOrgZero CHAR(1) DEFAULT 'N' NOT NULL CHECK (FIN_ForceOrgZero IN ('Y','N'));
ALTER TABLE AD_Column ADD COLUMN HST_IsHstColumn CHAR(1) DEFAULT 'N';
ALTER TABLE AD_Process ADD COLUMN AD_InfoWindow_ID NUMERIC(10);
ALTER TABLE AD_Table ADD COLUMN HST_HistoryMode VARCHAR(1) DEFAULT 'N';
ALTER TABLE AD_Table ADD COLUMN HST_IsForceHstApplication CHAR(1) DEFAULT 'N';
ALTER TABLE AD_Tree ADD COLUMN C_Element_ID NUMERIC(10);
ALTER TABLE AD_Tree ADD COLUMN HSTFromDate TIMESTAMP WITHOUT TIME ZONE DEFAULT current_timestamp;
ALTER TABLE AD_Tree ADD COLUMN HSTIsPrimaryTree CHAR(1) DEFAULT 'N';
ALTER TABLE AD_Tree ADD COLUMN HSTParentTree_ID NUMERIC(10);
ALTER TABLE AD_Tree ADD COLUMN HSTToDate TIMESTAMP WITHOUT TIME ZONE DEFAULT current_timestamp;

-- ===== AD_Field iniettati su window standard =====
-- Sub-query dinamica per AD_Tab_ID (gli ID tab standard differiscono tra release).
INSERT INTO AD_Field (AD_Field_ID,AD_Tab_ID,AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,Description,Help,IsDisplayed,SeqNo,IsCentrallyMaintained,EntityType,AD_Field_UU,AD_FieldGroup_ID,DisplayLength,DisplayLogic,IsReadOnly,IsEncrypted,IsSameLine,IsHeading,IsFieldOnly,XPosition,ColumnSpan) VALUES (1007643,(SELECT t.ad_tab_id FROM ad_tab t JOIN ad_window w ON w.ad_window_id = t.ad_window_id WHERE w.name = 'Report and Process' AND t.name = 'Report & Process' LIMIT 1),1005975,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Info Window','Info and search/select Window','The Info window is used to search and select records as well as display information relevant to the selection.','Y',100,'Y','FINHST','01d61b44-3f8d-41b9-9891-c4f65953c56d',NULL,0,NULL,'N','N','N','N','N',4,1);
INSERT INTO AD_Field (AD_Field_ID,AD_Tab_ID,AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,Description,Help,IsDisplayed,SeqNo,IsCentrallyMaintained,EntityType,AD_Field_UU,AD_FieldGroup_ID,DisplayLength,DisplayLogic,IsReadOnly,IsEncrypted,IsSameLine,IsHeading,IsFieldOnly,XPosition,ColumnSpan) VALUES (1007644,(SELECT t.ad_tab_id FROM ad_tab t JOIN ad_window w ON w.ad_window_id = t.ad_window_id WHERE w.name = 'Table and Column' AND t.name = 'Table' LIMIT 1),1005976,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'History Mode','History Mode for the table',NULL,'Y',140,'Y','FINHST','b31cdc0c-b957-4bcd-81b2-cd05c1b2ee8a',NULL,1,NULL,'N','N','N','N','N',1,1);
INSERT INTO AD_Field (AD_Field_ID,AD_Tab_ID,AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,Description,Help,IsDisplayed,SeqNo,IsCentrallyMaintained,EntityType,AD_Field_UU,AD_FieldGroup_ID,DisplayLength,DisplayLogic,IsReadOnly,IsEncrypted,IsSameLine,IsHeading,IsFieldOnly,XPosition,ColumnSpan) VALUES (1007645,(SELECT t.ad_tab_id FROM ad_tab t JOIN ad_window w ON w.ad_window_id = t.ad_window_id WHERE w.name = 'Table and Column' AND t.name = 'Table' LIMIT 1),1005977,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Is Force Hst Application','Force Applicability of the Historicizing ',NULL,'Y',180,'Y','FINHST','6ed6d683-a8f2-47c0-b3cb-e382dfd87d1f',NULL,1,'@IsView@=''N''','N','N','N','N','N',2,2);
INSERT INTO AD_Field (AD_Field_ID,AD_Tab_ID,AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,Description,Help,IsDisplayed,SeqNo,IsCentrallyMaintained,EntityType,AD_Field_UU,AD_FieldGroup_ID,DisplayLength,DisplayLogic,IsReadOnly,IsEncrypted,IsSameLine,IsHeading,IsFieldOnly,XPosition,ColumnSpan) VALUES (1007647,(SELECT t.ad_tab_id FROM ad_tab t JOIN ad_window w ON w.ad_window_id = t.ad_window_id WHERE w.name = 'Table and Column' AND t.name = 'Column' LIMIT 1),1005978,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Is Hst Column','Is Historicised Column',NULL,'Y',130,'Y','FINHST','b8baf157-b02d-459d-9bcb-8f1501ba4571',NULL,1,'@HST_HistoryMode@ =''S'' | @HST_HistoryMode@ =''T''','N','N','N','N','N',5,2);
INSERT INTO AD_Field (AD_Field_ID,AD_Tab_ID,AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,Description,Help,IsDisplayed,SeqNo,IsCentrallyMaintained,EntityType,AD_Field_UU,AD_FieldGroup_ID,DisplayLength,DisplayLogic,IsReadOnly,IsEncrypted,IsSameLine,IsHeading,IsFieldOnly,XPosition,ColumnSpan) VALUES (1007675,(SELECT t.ad_tab_id FROM ad_tab t JOIN ad_window w ON w.ad_window_id = t.ad_window_id WHERE w.name = 'Tree' AND t.name = 'Tree' LIMIT 1),1006006,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Primary Tree',NULL,NULL,'Y',130,'Y','FINHST','7d1e82f5-02b9-4d54-bdca-4a3004984241',NULL,1,NULL,'N','N','N','N','N',2,1);
INSERT INTO AD_Field (AD_Field_ID,AD_Tab_ID,AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,Description,Help,IsDisplayed,SeqNo,IsCentrallyMaintained,EntityType,AD_Field_UU,AD_FieldGroup_ID,DisplayLength,DisplayLogic,IsReadOnly,IsEncrypted,IsSameLine,IsHeading,IsFieldOnly,XPosition,ColumnSpan) VALUES (1007676,(SELECT t.ad_tab_id FROM ad_tab t JOIN ad_window w ON w.ad_window_id = t.ad_window_id WHERE w.name = 'Tree' AND t.name = 'Tree' LIMIT 1),1006007,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'Parent Tree',NULL,NULL,'Y',150,'Y','FINHST','4d7c052f-7d99-4bdf-b4ef-f1d0a8206c7c',NULL,10,'@HSTIsPrimaryTree@=N','N','N','Y','N','N',1,2);
INSERT INTO AD_Field (AD_Field_ID,AD_Tab_ID,AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,Description,Help,IsDisplayed,SeqNo,IsCentrallyMaintained,EntityType,AD_Field_UU,AD_FieldGroup_ID,DisplayLength,DisplayLogic,IsReadOnly,IsEncrypted,IsSameLine,IsHeading,IsFieldOnly,XPosition,ColumnSpan) VALUES (1007677,(SELECT t.ad_tab_id FROM ad_tab t JOIN ad_window w ON w.ad_window_id = t.ad_window_id WHERE w.name = 'Tree' AND t.name = 'Tree' LIMIT 1),1006004,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'From Date',NULL,NULL,'Y',170,'Y','FINHST','33bf5d46-21e8-4193-99d3-ba3c1552bc21',NULL,7,NULL,'N','N','N','N','N',1,1);
INSERT INTO AD_Field (AD_Field_ID,AD_Tab_ID,AD_Column_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,Description,Help,IsDisplayed,SeqNo,IsCentrallyMaintained,EntityType,AD_Field_UU,AD_FieldGroup_ID,DisplayLength,DisplayLogic,IsReadOnly,IsEncrypted,IsSameLine,IsHeading,IsFieldOnly,XPosition,ColumnSpan) VALUES (1007678,(SELECT t.ad_tab_id FROM ad_tab t JOIN ad_window w ON w.ad_window_id = t.ad_window_id WHERE w.name = 'Tree' AND t.name = 'Tree' LIMIT 1),1006005,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'To Date',NULL,NULL,'Y',180,'Y','FINHST','f1925245-0372-4490-8a8f-d9c8f198f97e',NULL,7,NULL,'N','N','Y','N','N',4,1);

-- ===== AD_ToolBarButton (HistoryRecords + HistoryRecordsTest) =====
-- Clonati 1:1 da SVI (ID 1000003/1000004 + UU stabili).
-- Cleanup ID provvisori 1000001/1000002 eventualmente inseriti in passato.
DELETE FROM AD_ToolBarButton WHERE AD_ToolBarButton_ID IN (1000001, 1000002);
INSERT INTO AD_ToolBarButton (AD_ToolBarButton_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ComponentName,ActionClassName,IsCustomization,EntityType,Action,IsAdvancedButton,IsAddSeparator,AD_ToolBarButton_UU) VALUES (1000003,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'History Records','HistoryRecords','it.finmatica.history.records.ui.zk.action.HistoryRecordsAction','Y','U','W','N','Y','7281b707-d374-4e6c-b1d7-53b4cbe056ce');
INSERT INTO AD_ToolBarButton (AD_ToolBarButton_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,ComponentName,ActionClassName,IsCustomization,EntityType,Action,IsAdvancedButton,IsAddSeparator,AD_ToolBarButton_UU) VALUES (1000004,0,0,'Y',CURRENT_TIMESTAMP,0,CURRENT_TIMESTAMP,0,'History Records Verify','HistoryRecordsTest','it.finmatica.history.records.ui.zk.action.HistoryRecordsVerifyAction','Y','U','W','N','N','afa20aa6-d001-4ef5-87c6-26109b52c788');
UPDATE AD_ToolBarButton SET DisplayLogic = '@SQL=select ''Y'' from ad_window inner join ad_tab on ad_window.ad_window_id = ad_tab.ad_window_id inner join ad_table on ad_table.ad_table_id = ad_tab.ad_table_id inner join ad_tab hsttab on hsttab.ad_window_id = ad_window.ad_window_id and hsttab.tablevel = ad_tab.tablevel + 1 and hsttab.seqno > ad_tab.seqno inner join ad_table hsttable on hsttable.ad_table_id = hsttab.ad_table_id where ad_window.ad_window_id=@_WinInfo_AD_Window_ID@ and ad_tab.ad_tab_id = @_TabInfo_AD_Tab_ID@ and ad_table.hst_historymode in (''S'',''T'') and ad_table.tablename||''_HST'' = hsttable.tablename' WHERE AD_ToolBarButton_ID = 1000003;
UPDATE AD_ToolBarButton SET DisplayLogic = '@SQL=select distinct ''Y'' from HST_UpdCheckConf where ad_table_id = @_TabInfo_AD_Table_ID@' WHERE AD_ToolBarButton_ID = 1000004;
