src.excludes = test/
# scoletta@ads.it - History Records Plugin
# META-INF/ include automaticamente MANIFEST.MF + 2Pack_*.zip (Incremental2PackActivator).
bin.includes = META-INF/,\
               .,\
               OSGI-INF/historysqlrewriter.xml,\
               OSGI-INF/historyvalidatorfactory.xml,\
               OSGI-INF/,\
               OSGI-INF/hstprocessfactory.xml,\
               OSGI-INF/hstmodelfactory.xml,\
               OSGI-INF/historyevent.xml,\
               OSGI-INF/historyuibehaviour.xml,\
               lib/
source.. = src/
output.. = target/classes/
